#!/bin/bash
# ===============================================
# This script file was generated by maxinet
# Author: Arafat Ali | Email: admin@sofibox.com | Web: sofibox.com
# ===============================================
# Using --setup will trigger setup script from maxinet
cd /root || exit 1
chmod +x maxinet
touch maxinet.log
./maxinet --setup 2>&1 | tee maxinet.log
echo ""
