#!/bin/bash
# ===============================================
# This script file was automatically generated by maxinet
# Author: Arafat Ali | Email: admin@sofibox.com | Web: sofibox.com
# ===============================================
# Using --force to ignore any prompts when rebooting. Such as the prompt to eject DISK and waiting for user input
reboot --force
# Put 2 times exit below to safely exit the script if the first exit is not executed
exit
exit
