#!/bin/bash
# ===============================================
# This script file was generated by maxinet
# Author: Arafat Ali | Email: admin@sofibox.com | Web: sofibox.com
# ===============================================
# Using --force to ignore any prompts when rebooting. Such as the prompt to eject DISK and waiting for user input
reboot --force
echo ""
