#!/bin/bash
# ===============================================
# This script file was generated by maxinet
# Author: Arafat Ali | Email: admin@sofibox.com | Web: sofibox.com
# ===============================================
# This is just a test script
touch test_file
# Put 2 times exit below to safely exit the script if the first exit is not executed
exit
exit
